### ISSUE TITLE
NFL Logo with white frame/background

### ISSUE THREAD

**Issue by kif23** [robbydyer/sports#306]
it's me again...

just activated the NFL, and the logo 

https://github.com/robbydyer/sports/blob/master/internal/espnboard/assets/league_logos/nfl.png

has an ugly white frame/background around it on the matrix as well as on the web ui

![image](https://user-images.githubusercontent.com/5486398/182788908-f53b8983-5b37-4a85-867a-a273ff14f341.jpeg)

**Comment by robbydyer** [comment]
v0.0.90 has the new NFL log. 

You will need to clear your logo cache. You can either reboot the Pi, or run:
```
sudo rm -rf /tmp/sportsmatrix*
```

**Comment by kif23** [comment]
perfect! thanks!

when will your [Roadmap](https://github.com/robbydyer/sports#roadmap) be up? i've found some more of these :)

**Comment by robbydyer** [comment]
That Roadmap used to contain the high-level boards I wanted to add, but I've since added them all. I don't really have a roadmap currently. For the most updated info on what I'm planning to work on or to share ideas, I recommend joining the Discord channel. Folks give ideas for improvements and new features in there pretty often.

**Comment by robbydyer** [comment]
https://discord.gg/8vPp4xfdtV
