### ISSUE TITLE
Suggestion: Outline for White Font to Stand Out Against White Logos?

### ISSUE THREAD

**Issue by nboggess18** [robbydyer/sports#456]
Hi,

Would it be possible to implement a colored/black outline for the white score/records font? I have noticed that it can be difficult to read scores/records when the team logos behind them are white. Perhaps something similar to the way that betting odds are encased in a black box?

Thanks for your consideration!

**Comment by robbydyer** [comment]
Could you possibly provide an example of the issue? The team record is already written with a black box around it, so that shouldn't be washed out by the logo. 

As for the score, I would suggest ensuring that you have the `useGradient` setting for each sport set to `true`, if you don't already- that setting makes score legibility a lot better for smaller scoreboards. (https://github.com/robbydyer/sports/blob/master/sportsmatrix.conf.example#L247)

**Comment by nboggess18** [comment]
![PXL_20221221_173518120](https://user-images.githubusercontent.com/17804759/208972663-1873092e-81cb-4cdc-87ca-07d4da3d667a.jpg)

This photo may show a good example of the tight spacing on my display between score, record, and the breadcrumb navigation on the bottom. You can see that it's a bit tricky to distinguish the "1" at the beginning of the Wizards's score.

**Comment by robbydyer** [comment]
Try setting `useGradient: false` in your NBA section. That should make it draw a black box outline. 

It's perhaps a bit confusing but there are actually 3 different states that result from the `useGradient` setting:
- If this setting is not configured at all (or commented out in the config), you get no gradient and no black box
- If set to `true`, the team logos fade in the center of the board and makes the score more readable
- If set to `false`, the score is surrounded with the black box.

**Comment by nboggess18** [comment]
Thank you for that suggestion! That definitely helps!
