### ISSUE TITLE
hardwareMapping

### ISSUE THREAD

**Issue by sgil0609** [robbydyer/sports#69]
I am trying to change the config file hardwareMapping to regular vice adafruit-hat.  It does not seem to work once that has been changed.  Also, for the scrolling portion, is there an option to have one sport score come after the other vice waiting for it to come across the entire screen?

**Comment by robbydyer** [comment]
For the hardware change, you can modify it in your config file, which is `/etc/sportsmatrix.conf`, then restart the service with `sudo systemctl restart sportsmatrix`. Any changes to the config file will require restarting the service.

As for the scrolling- having the scores scroll back to back without clearing the entire screen is unfortunately not something I can easily make work, given how things are rendered. The scrolling mode wasn't in the initial plans, so I didn't account for the back-to-back ability early on.

**Comment by sgil0609** [comment]
Thank you for your reply.  Would the scrolling require a complete rework?
The only reason I ask as I am new to this entire language/project and
trying to learn. Any reading material/references you have are greatly
appreciated

**Comment by robbydyer** [comment]
It wouldn't necessarily require a "complete rework", but it would require a bit more work than I'm interested in doing currently. 

The gist of it is, each game score is rendered in memory individually (so that scores are as up to date as possible), then drawn to the screen. The scroll mode simply takes a rendered board and shifts it across the screen instead of drawing it once. Having the scores trail back-to-back means it would instead need to render *all* of the scores at once, then scroll it. It's certainly doable, just doesn't fit cleanly into the way things are laid out currently. Getting it to scroll back-to-back across different sports would require even more work. There's also the side-effect that the scores would then only be up to date as of when that sport was specifically rendered- in reality that probably isn't a big deal.

As for reading materials, that depends on your experience writing software in general. You'd either need some intro to programming types of materials, or just some intro to Go (the language used in this project) materials. I don't have any specific things to point you to, unfortunately.

**Comment by sgil0609** [comment]
I understand. My ideal would be to have 4 to 6 panels in series with the
sports scrolling across them, this is the basis of my questions  Secondly,
my dream would be to connect those games back to somewhere offering me the
current odds for the games for the man cave!  I would poke around/break the
code and try to play with some of it. I truely do appreciate you answering
to the questions. If I am unable to do this myself, do you have a price
that you would be willing to do it/educate me on the process?

**Comment by robbydyer** [comment]
Oh ok, you want it to look better with wider screen setups. 

Message me on discord if you want to talk specifics robby#4872

**Comment by BensBar** [comment]
Robby, which discord server are you on?  I am trying to reach-out but it says you don't accept messages from non friends.  Sorry, a noob on Discord.

**Comment by robbydyer** [comment]
I just created a public server "RGB Sportsmatrix Help" https://discord.gg/UUkr4DvG
